---
platform: linux
image_resource:
  type: docker-image
  source: {repository: "java", tag: "8"}
params:
  HOSTEDGRAPHITE_APIKEY: {{hostedgraphite-apikey}}
  HOSTEDGRAPHITE_URL: {{hostedgraphite-url}}
  HOSTEDGRAPHITE_PORT: {{hostedgraphite-port}}
inputs:
- name: github
outputs:
- name: jar
run:
  path: sh
  args:
  - -exc
  - |
    cd github && ./mvnw install && mv target/demo*.jar ../jar/demo.jar