---
platform: linux
image_resource:
  type: docker-image
  source: {repository: "java", tag: "8"}
inputs:
- name: github
outputs:
- name: jar
run:
  path: sh
  args:
  - -exc
  - |
    cd github && ./mvnw install && mv target/rr*.jar ../jar/rr.jar