---
resources:
- name: github
  type: git
  source:
    uri: https://github.com/joshlong/operationalized-applications-meetup
    branch: master
- name: pws
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{pws-username}}
    password: {{pws-password}}
    organization: {{pws-organization}}
    space: {{pws-space}}

jobs:
- name: make-jar-not-war
  plan:
  - get: github
  - task: maven
    file: github/ci/tasks/build.yml
  - put: pws
    params:
      path: jar/demo.jar
      current_app_name: operationalized-applications
      manifest: github/manifest.yml