---
resource_types:
- name: cf-working
  type: docker-image
  source:
    repository: caseywest/cf-release

resources:
- name: github
  type: git
  source:
    uri: https://github.com/joshlong/operationalized-applications-meetup
    branch: master
- name: pivotal-web-services
  type: cf-working
  source:
    api: https://api.run.pivotal.io
    username: {{pws-username}}
    password: {{pws-password}}
    organization: {{pws-organization}}
    space: {{pws-space}}

jobs:
- name: make-jar-not-war
  plan:
  - get: github
    trigger: true
  - task: maven-install
    params:
      HOSTEDGRAPHITE_APIKEY: {{hostedgraphite-apikey}}
      HOSTEDGRAPHITE_URL: {{hostedgraphite-url}}
      HOSTEDGRAPHITE_PORT: {{hostedgraphite-port}}
    file: github/ci/tasks/build.yml
  - put: pivotal-web-services
    params:
      path: jar/rr.jar
      current_app_name: operationalized-applications
      manifest: github/manifest.yml